# 商店商品定义
# 每个商品: name, price, hunger, happiness, energy, desc, icon

ITEMS = [
    {
        "id": "basic_chip",
        "name": "基础芯片",
        "icon": "💾",
        "price": 10,
        "hunger": 30,
        "happiness": 0,
        "energy": 0,
        "desc": "基础能源芯片，管饱",
    },
    {
        "id": "crypto_candy",
        "name": "加密糖果",
        "icon": "🍬",
        "price": 25,
        "hunger": 15,
        "happiness": 20,
        "energy": 0,
        "desc": "稀有数据糖，吃了超开心",
    },
    {
        "id": "cooling_module",
        "name": "散热模块",
        "icon": "❄️",
        "price": 20,
        "hunger": 40,
        "happiness": 5,
        "energy": 0,
        "desc": "高效散热，稳定运行",
    },
    {
        "id": "energy_core",
        "name": "能量核心",
        "icon": "🔋",
        "price": 15,
        "hunger": 5,
        "happiness": 10,
        "energy": 30,
        "desc": "补充电力，瞬间恢复精力",
    },
    {
        "id": "data_fragment",
        "name": "数据碎片",
        "icon": "💎",
        "price": 30,
        "hunger": 0,
        "happiness": 30,
        "energy": -5,
        "desc": "珍贵的数据，玩累了但快乐",
    },
    {
        "id": "quantum_coprocessor",
        "name": "量子协处理器",
        "icon": "⚛️",
        "price": 50,
        "hunger": 60,
        "happiness": 30,
        "energy": 20,
        "desc": "终极升级组件，土豪之选",
    },
]
